import { Organisation } from "@/schemas/Organisation.monkko";
import { createModel } from "@monkko/orm/models";
import { MongoClient } from "@/lib/MongoClient";
import type { ObjectId } from "mongodb";

// This type would be auto-generated by the CLI in the future
export type OrganisationDocument = {
  _id: ObjectId;
  name: string;
  description?: string;
  website?: string;
  industry?: string;
}

const organisationModel = createModel<OrganisationDocument>(Organisation, MongoClient);

export default organisationModel;
