import { Organisation } from "@/schemas/Organisation.monko";
import { createModel } from "@monko/orm/models";
import { MongoClient } from "@/lib/MongoClient";

// This type would be auto-generated by the CLI in the future
export type OrganisationDocument = {
  _id: string; // Using string for now, would be ObjectId in generated types
  name: string;
  description?: string;
  website?: string;
  industry?: string;
}

const organisationModel = createModel<OrganisationDocument>(Organisation, MongoClient);

export default organisationModel;
