import { User } from "@/schemas/User.monko";
import { createModel } from "@monko/orm/models";
import { MongoClient } from "@/lib/MongoClient";
import type { OrganisationDocument } from "./Organisation";

// This type would be auto-generated by the CLI in the future
export type UserDocument = {
  _id: string; // Using string for now, would be ObjectId in generated types
  name: string;
  email: string;
  address?: {
    street: string;
    city: string;
    state: string;
    zip: string;
  };
  organisationId?: string | OrganisationDocument; // Union type for populate!
}

const userModel = createModel<UserDocument>(User, MongoClient);

export default userModel;